#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    dirs="$(cat $HOME/.tmux-sessionizer-dirs | tr '\n' ' ')"
    selected=$(eval find ~/ $dirs -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# if tmux is not running, or we are not in a tmux session and the selected session does not exist, create a new session
if [[ -z $tmux_running ]] || ([[ -z $TMUX ]] && ! tmux ls | grep -q $selected_name); then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

# if we are not in a tmux session and the selected session exists, attach to it
if [[ -z $TMUX ]] && tmux ls | grep -q $selected_name; then
    tmux attach-session -t $selected_name
    exit 0
fi
# if we are in a tmux session and the selected session does not exist, create a new session
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
